apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-com
spec:
  secretName: generated
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "test.com"
  dnsNames:
    - test.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
